### ISSUE TITLE
Modelu "torchgeo" with problems

### ISSUE THREAD

**Issue by ANDYAGUIRRE10** [coolzhao/Geo-SAM#14]
Hello! Thanks a lot for your work.
I attached a problem when I am installing the plugin. 
No se pudo cargar el complemento 'Geo-SAM' 

ModuleNotFoundError: No module named 'torchgeo' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\__init__.py", line 7, in 
    from .geo_sam_tool import Geo_SAM
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\geo_sam_tool.py", line 24, in 
    from .tools.SAMTool import SAM_Model
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\SAMTool.py", line 13, in 
    from .torchgeo_sam import SamTestFeatureDataset, SamTestFeatureGeoSampler
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\torchgeo_sam.py", line 21, in 
    from torchgeo.datasets import unbind_samples, stack_samples, BoundingBox, RasterDataset, GeoDataset, IntersectionDataset
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'torchgeo'

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.26.0-Buenos Aires Buenos Aires, 0aece2818e 

Ruta de Python:
C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometric_attributes
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.26.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.26.0\bin
C:\Users\Usuario\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs

Grettings from Argentina!

**Comment by Fanchengyan** [comment]
Hi @ANDYAGUIRRE10 , you are expected to have installed the dependences before open QGIS. Please follow the Installation in Readme.

![image](https://github.com/coolzhao/Geo-SAM/assets/24694181/1745d7b5-bad7-47b1-8aff-189889fff3f8)
