### ISSUE TITLE
install error on Windows

### ISSUE THREAD

**Issue by initze** [coolzhao/Geo-SAM#2]
Hi,
unfortunately I wasn't able to install the plugin

1. I installed dependencies (perhaps sth wrong)
2. . Tried installing the zip and the following error popped up

```
Couldn't load plugin 'Geo-SAM-1.0.5' 

ModuleNotFoundError: No module named 'Geo-SAM-1' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\Users/initze/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Geo-SAM-1'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.1-'s-Hertogenbosch 's-Hertogenbosch, 9035a01e 

Python Path:
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/initze/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/initze/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass82\etc\python
C:\Users\initze\Documents
C:\Program Files\QGIS 3.30.1\bin\python39.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.30.1\bin
C:\PROGRA~1\QGIS33~1.1\apps\Python39
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/initze/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\initze\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
```

**Comment by stewe12** [comment]
Hi, you need to remove number from the zip of the plugin. You can see it on third row in the code you pasted.

QGis doesn't understand numbers in the name of plugin.

**Comment by initze** [comment]
This seems to be the issue:
Unzip --> rename --> zip --> install
Now I am having trouble installing torchgeo (dependency pretrainedmodels crashes on pip install 😵‍💫 )

**Comment by coolzhao** [comment]
Hi Ingmar, 

Sorry for the late reply. Yes, the version suffix issue is a problem that many users may encounter.
Can you successfully install the dependencies and plugin now? 
If you got any problem, feel free to let me know by email.

Joey
