### ISSUE TITLE
ModuleNotFoundError: No module named 'rasterio'

### ISSUE THREAD

**Issue by mikdotou** [coolzhao/Geo-SAM#23]
When I finish installation I get this error.

_```
Impossible de charger l'extension 'Geo-SAM' 

ModuleNotFoundError: No module named 'rasterio' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\__init__.py", line 7, in 
    from .geo_sam_tool import Geo_SAM
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\geo_sam_tool.py", line 24, in 
    from .tools.SAMTool import SAM_Model
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\SAMTool.py", line 7, in 
    import rasterio
  File "C:\PROGRA~1/QGIS32~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'rasterio'
```_

Could you help me to fix it ?
Thanks

**Comment by Fanchengyan** [comment]
Have you installed dependencies? `rasterio` should be installed after installing `torchgeo` . If not, please follow the tutorial step-by-step to install them: <https://geo-sam.readthedocs.io/en/latest/Installation.html#install-library-dependencies>
