### ISSUE TITLE
Failed to load plugin QGIS 3.38.0 

### ISSUE THREAD

**Issue by cullenfranchino1** [coolzhao/Geo-SAM#45]
using [Geo-SAM v1.3-rc] also will not load in qgis 3.32.2 . I know after 3.32.2 QGIS has started blocking certain dependencies, for example influxdb is something that has been blocked. Any way to fix this?

Couldn't load plugin 'Geo-SAM' 

ModuleNotFoundError: No module named 'Geo-SAM.docs' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 404, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\__init__.py", line 7, in 
    from .geo_sam_tool import Geo_SAM
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\geo_sam_tool.py", line 12, in 
    from .geo_sam_provider import GeoSamProvider
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\geo_sam_provider.py", line 7, in 
    from .tools.sam_processing_algorithm import SamProcessingAlgorithm
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\sam_processing_algorithm.py", line 53, in 
    from ..docs import encoder_help
  File "C:\PROGRA~1/QGIS33~3.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Geo-SAM.docs'

Python version: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.38.0-Grenoble Grenoble, 37aa6188bc 

Python Path:
C:/PROGRA~1/QGIS33~3.0/apps/qgis/./python
C:/Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~3.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~3.0\apps\grass\grass83\etc\python
C:\Users\culle\Documents
C:\Program Files\QGIS 3.38.0\bin\python312.zip
C:\PROGRA~1\QGIS33~3.0\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~3.0\apps\Python312\Lib
C:\Program Files\QGIS 3.38.0\bin
C:\Users\culle\AppData\Roaming\Python\Python312\site-packages
C:\PROGRA~1\QGIS33~3.0\apps\Python312
C:\PROGRA~1\QGIS33~3.0\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~3.0\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~3.0\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~3.0\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/culle/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:\Users\culle\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl

**Comment by cullenfranchino1** [comment]
nevermind!
