### ISSUE TITLE
GeoSAM plugin fails to load ValueError

### ISSUE THREAD

**Issue by klara4390** [coolzhao/Geo-SAM#47]
Hi - I am quite new to using python - so I probably don't have all the necessary details included in the first try - let me know what is missing. 

Trying to load the plugin from the QGIS plugin manager gives following error:
**ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject** 

I am using 3.34.10-Prizren and Python 3.9.5. 

Hope someone can help :)

**Comment by Fanchengyan** [comment]
Hi @klara4390 

Did you adhere to the installation steps on https://geo-sam.readthedocs.io/en/latest/installation.html? Besides, please share the full error message to help us diagnose the problem.

**Comment by klara4390** [comment]
I did - Today QGIS is for some reason able to load the plugin, but the following error message is given when testing segmentation on the beiluhe image. 

**From "python error":**
raceback (most recent call last):
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/geo_sam_tool.py", line 403, in execute_segmentation
              if not self.sam_model.sam_predict(
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/SAMTool.py", line 94, in sam_predict
              self.sample = self.test_features[query]
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/torchgeo_sam.py", line 376, in __getitem__
              tensor = torch.tensor(dest) # .float()
             RuntimeError: Could not infer dtype of numpy.float32

**From the "python warning":**

2024-09-11T11:02:27     WARNING    warning:/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
              device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/pyplugin_installer/installer.py", line 284, in showPluginManagerWhenReady
              iface.pluginManagerInterface().showPluginManager(tabIndex)
              File "", line 1, in 
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 391, in loadPlugin
              __import__(packageName)
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/__init__.py", line 7, in 
              from .geo_sam_tool import Geo_SAM
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/geo_sam_tool.py", line 24, in 
              from .tools.SAMTool import SAM_Model
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/SAMTool.py", line 12, in 
              from torch.utils.data import DataLoader
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 972, in _find_and_load_unlocked
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 972, in _find_and_load_unlocked
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/__init__.py", line 1477, in 
              from .functional import * # noqa: F403
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/functional.py", line 9, in 
              import torch.nn.functional as F
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 972, in _find_and_load_unlocked
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in 
              from .modules import * # noqa: F403
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in 
              from .transformer import TransformerEncoder, TransformerDecoder, \
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in 
              device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
             
2024-09-11T11:02:40     WARNING    warning:/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg/pyproj/__init__.py:91: UserWarning: Valid PROJ data directory not found. Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
              warnings.warn(str(err))
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/pyplugin_installer/installer.py", line 284, in showPluginManagerWhenReady
              iface.pluginManagerInterface().showPluginManager(tabIndex)
              File "", line 1, in 
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 391, in loadPlugin
              __import__(packageName)
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/__init__.py", line 7, in 
              from .geo_sam_tool import Geo_SAM
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/geo_sam_tool.py", line 24, in 
              from .tools.SAMTool import SAM_Model
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/SAMTool.py", line 13, in 
              from .torchgeo_sam import SamTestFeatureDataset, SamTestFeatureGeoSampler
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/torchgeo_sam.py", line 21, in 
              from torchgeo.datasets import unbind_samples, stack_samples, BoundingBox, RasterDataset, GeoDataset, IntersectionDataset
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torchgeo/datasets/__init__.py", line 6, in 
              from .advance import ADVANCE
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torchgeo/datasets/advance.py", line 17, in 
              from .geo import NonGeoDataset
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torchgeo/datasets/geo.py", line 19, in 
              import pyproj
              File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg/pyproj/__init__.py", line 91, in 
              warnings.warn(str(err))

**Comment by klara4390** [comment]
And similar error when trying to encode an image: 

Traceback (most recent call last):
File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/sam_processing_algorithm.py", line 527, in processAlgorithm
for current, batch in enumerate(ds_dataloader):
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
data = self._next_data()
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/Users/klarasorensen/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Geo-SAM/tools/torchgeo_sam.py", line 485, in __getitem__
tensor = torch.tensor(dest) # .float()
RuntimeError: Could not infer dtype of numpy.int32

Execution failed after 9.70 seconds

**Comment by Fanchengyan** [comment]
This issue appears to stem from an incompatibility between certain versions of PyTorch and NumPy. 

https://stackoverflow.com/questions/74722112/runtimeerror-could-not-infer-dtype-of-numpy-float32-when-trying-to-learn-ml-a

https://github.com/Unity-Technologies/ml-agents/issues/6010

 Try to update or downgrade your NumPy version to see if it works.

**Comment by Fanchengyan** [comment]
Hi @klara4390 

I encountered this issue on macOS as well. I was able to resolve it by updating the versions of `numpy` and `pandas`:

```bash
cd /Applications/QGIS.app/Contents/MacOS/bin

./pip3 install numpy pandas -U
```
