### ISSUE TITLE
QgsField Type Error

### ISSUE THREAD

**Issue by jtgilbert** [coolzhao/Geo-SAM#60]
QGIS version: 3.34.4-Prizren
QGIS code revision: decd43dc
Qt version: 5.15.3
Python version: 3.9.18
GDAL/OGR version: 3.8.4
PROJ version: 9.3.1
EPSG Registry database version: v11.016 (2024-08-31)
GEOS version: 3.12.1-CAPI-1.18.1
SQLite version: 3.41.1
PDAL version: 2.6.0
PostgreSQL client version: 16.1
SpatiaLite version: 5.1.0
QWT version: 6.1.6
QScintilla2 version: 2.13.4
OS version: Windows 10 Version 2009

2024-12-23T10:50:53     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
              __import__(packageName)
              File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\__init__.py", line 7, in 
              from .geo_sam_tool import Geo_SAM
              File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\geo_sam_tool.py", line 10, in 
              from .tools.widgetTool import Selector, EncoderCopilot
              File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\widgetTool.py", line 32, in 
              from .canvasTool import (
              File "C:\PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/jordang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Geo-SAM\tools\canvasTool.py", line 58, in 
              QgsField("group_ulid", QMetaType.QString),
             TypeError: QgsField(): arguments did not match any overloaded call:
              overload 1: argument 2 has unexpected type 'Type'
              overload 2: argument 1 has unexpected type 'str'

**Comment by Fanchengyan** [comment]
Hi @jtgilbert 

Thanks for your feedback. We have addressed the issues in the [new release](https://github.com/coolzhao/Geo-SAM/releases/tag/v1.3.1-rc3). You can the zipped file labeled `*_code_update.zip` to update the plugin.
